services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sweet-bakery-frontend
    ports:
      - "8081:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3
